services:
  - type: web
    name: token-auth-api
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn myproject.wsgi"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key-here
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
